import random as rn
import time as tm


question = input("What is your question: ") #initial input
print("Thinking ...")
tm.sleep(8) #provides suspense using sleep function
print("Your question was: " + question) #regurgitates question back at user
tm.sleep(5) #provides more suspense, not needed, just made me feel better when running the code, more smooth.
shuffle = rn.randint(0,3)
if shuffle == 0: #if the number generated by randint is 1, the answer will be yes
    print("My answer is: yes")
if shuffle == 1: #if the number generated by randint is 1 (in this case 0), the answer will be no
    print("My answer is: no")
if shuffle == 2:
    print("My answer is: time will tell. do not worry about it")
if shuffle == 3:
    print("My answer is: ask a friend. they will know")
